# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./WindowAndDialogExamples.h
SOURCES += ./WindowAndDialogExamples.cpp \
    ./main.cpp
FORMS += ./WindowAndDialogExamples.ui
RESOURCES += WindowAndDialogExamples.qrc
