# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./InputExamples.h
SOURCES += ./InputExamples.cpp \
    ./main.cpp
RESOURCES += InputExamples.qrc
