# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./DisplayWidgetExamples.h
SOURCES += ./DisplayWidgetExamples.cpp \
    ./main.cpp
RESOURCES += DisplayWidgetExamples.qrc
